#!/usr/bin/env python3
from pathlib import Path


def once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f"Alice5.1 anchor missing: {label}")
    return text.replace(old, new, 1)

# Identity: 5.1 is an update over the validated 5.0 command bridge.
p = Path("app/build.gradle.kts")
s = p.read_text()
s = once(s, "versionCode = 64011", "versionCode = 64012", "versionCode")
s = once(
    s,
    'versionName = "3.15.2-alice5.0-command-bridge"',
    'versionName = "3.15.2-alice5.1-app-bridge"',
    "versionName",
)
p.write_text(s)

# ---------------------------------------------------------------------------
# Extend CommandTranslator AFTER Build 5.0 has installed dynamic window support.
# ---------------------------------------------------------------------------
p = Path("app/src/main/kotlin/com/bydmate/app/data/vehicle/CommandTranslator.kt")
s = p.read_text()

s = once(
    s,
    '''        "打开空调通风" to Resolved("ac_flow_only_on",   1),  // competitor val=1
        "吹前挡"      to Resolved("defrost_front_on",  1),  // competitor val=1
''',
    '''        "打开空调通风" to Resolved("ac_flow_only_on",   1),  // competitor val=1
        "关闭空调通风" to Resolved("ac_flow_only_off",  0),  // competitor val=0
        "吹前挡"      to Resolved("defrost_front_on",  1),  // competitor val=1
''',
    "flow-only off command",
)

s = once(
    s,
    '''        TEMP_REGEX.matchEntire(stripped)?.let { m ->
            val celsius = m.groupValues[1].toInt().coerceIn(TEMP_MIN, TEMP_MAX)
            return listOf(Resolved("ac_temp_main", celsius))
        }
        // Dynamic fridge setpoints: 冰箱制冷<N>度 / 冰箱制热<N>度 for ANY N — the agent
''',
    '''        TEMP_REGEX.matchEntire(stripped)?.let { m ->
            val celsius = m.groupValues[1].toInt().coerceIn(TEMP_MIN, TEMP_MAX)
            return listOf(Resolved("ac_temp_main", celsius))
        }
        // Alice 5.1 fan level. BYD exposes 0..7 through ac_wind_level / setAcWindLevel.
        FAN_LEVEL_REGEX.matchEntire(stripped)?.let { m ->
            val level = m.groupValues[1].toIntOrNull() ?: return emptyList()
            if (level !in FAN_LEVEL_MIN..FAN_LEVEL_MAX) return emptyList()
            return listOf(Resolved("ac_wind_level", level))
        }
        // Dynamic fridge setpoints: 冰箱制冷<N>度 / 冰箱制热<N>度 for ANY N — the agent
''',
    "dynamic fan level",
)

s = once(
    s,
    '''    private const val TEMP_MAX = 30

    // Dynamic fridge commands: 冰箱制冷<N>度 (cool, C in -6..6) / 冰箱制热<N>度 (heat, 35..50).
''',
    '''    private const val TEMP_MAX = 30

    private val FAN_LEVEL_REGEX = Regex("""风量(\\d+)""")
    private const val FAN_LEVEL_MIN = 0
    private const val FAN_LEVEL_MAX = 7

    // Dynamic fridge commands: 冰箱制冷<N>度 (cool, C in -6..6) / 冰箱制热<N>度 (heat, 35..50).
''',
    "fan level regex",
)

s = once(
    s,
    '''    private val DYNAMIC_ACTIONS = setOf(
        "ac_temp_main",
        "window_driver_pos",
        "window_passenger_pos",
        "window_rear_left_pos",
        "window_rear_right_pos",
    )
''',
    '''    private val DYNAMIC_ACTIONS = setOf(
        "ac_temp_main",
        "ac_wind_level",
        "window_driver_pos",
        "window_passenger_pos",
        "window_rear_left_pos",
        "window_rear_right_pos",
    )
''',
    "fan dynamic action invariant",
)
p.write_text(s)

# The competitor catalog contains ac_wind_level without a fixed value. Production
# parsing therefore sees it as 0..0. Stage the real BYD 0..7 range explicitly so
# VehicleApi can test all fan levels while still going through the allowlist.
p = Path("app/src/main/kotlin/com/bydmate/app/data/vehicle/WriteAllowlist.kt")
s = p.read_text()
s = once(
    s,
    '''        val CANDIDATE_UNVALIDATED: List<WriteEntry> = listOf(
            // Seat heat/vent fallback channel — competitor dev=1001, single write.
''',
    '''        val CANDIDATE_UNVALIDATED: List<WriteEntry> = listOf(
            // Alice 5.1 test surface: BYD AC fan level 0..7 (dev=1000/fid=501219340).
            // The SDK exposes AC_WINDLEVEL_0..7; this exact FID comes from the competitor
            // catalog. Kept candidate/unvalidated until the user completes the in-car matrix.
            WriteEntry("ac_wind_level", 1000, 501219340, null, 0, 7, "climate", false, "alice5.1-field-test"),

            // Seat heat/vent fallback channel — competitor dev=1001, single write.
''',
    "fan range candidate",
)
p.write_text(s)

# ---------------------------------------------------------------------------
# AlicePollingManager is generated by Build 5.0. Extend the hardened baseline.
# ---------------------------------------------------------------------------
p = Path("app/src/main/kotlin/com/bydmate/app/data/remote/AlicePollingManager.kt")
s = p.read_text()

s = once(
    s,
    '''    private val sharedAdaptiveLoop: com.bydmate.app.data.loop.SharedAdaptiveLoop,
    private val vehicleApi: VehicleApi,
) {
''',
    '''    private val sharedAdaptiveLoop: com.bydmate.app.data.loop.SharedAdaptiveLoop,
    private val vehicleApi: VehicleApi,
    private val appCommandDispatcher: AliceAppCommandDispatcher,
) {
''',
    "AlicePollingManager app dispatcher injection",
)

s = once(
    s,
    '''            val resolved = AliceBridgeCommandTranslator.resolve(cmd)
            if (resolved == null) {
                val requested = cmd.optString("action", "<missing>")
                Log.w(TAG, "BRIDGE_COMMAND_REJECTED id=$id action=$requested reason=unsupported_or_invalid")
                rememberResult(id, requested, false, "unsupported_or_invalid")
                results += AckResult(id, false, "unsupported_or_invalid")
                continue
            }

            val command = resolved.vehicleCommand
''',
    '''            val requested = cmd.optString("action", "<missing>").trim().lowercase()

            // Alice 5.1 local Android actions (apps/media/projection). They never enter
            // VehicleApi or the BYD raw-write path.
            val appResult = appCommandDispatcher.dispatch(cmd)
            if (appResult != null) {
                val success = appResult.isSuccess
                val error = appResult.exceptionOrNull()?.message
                Log.i(TAG, "BRIDGE_APP_COMMAND_RECEIVED id=$id action=$requested")
                rememberResult(id, requested, success, error)
                Log.i(TAG, "BRIDGE_APP_COMMAND_RESULT id=$id action=$requested success=$success" +
                    (error?.let { " error=${it.take(160)}" } ?: ""))
                results += AckResult(id, success, error?.take(240))
                continue
            }

            val resolved = AliceBridgeCommandTranslator.resolve(cmd)
            if (resolved == null) {
                Log.w(TAG, "BRIDGE_COMMAND_REJECTED id=$id action=$requested reason=unsupported_or_invalid")
                rememberResult(id, requested, false, "unsupported_or_invalid")
                results += AckResult(id, false, "unsupported_or_invalid")
                continue
            }

            val command = resolved.vehicleCommand

            // Rear tailgate remote-open is stricter than the generic local automation
            // path: Alice may be invoked remotely, so require a known standstill.
            if (resolved.action == "trunk.rear.open") {
                val speed = latestData?.speed
                if (speed == null || speed > 0) {
                    val reason = if (speed == null) "rear_trunk_speed_unknown" else "rear_trunk_moving:$speed"
                    Log.w(TAG, "BRIDGE_COMMAND_REJECTED id=$id action=${resolved.action} reason=$reason")
                    rememberResult(id, resolved.action, false, reason)
                    results += AckResult(id, false, reason)
                    continue
                }
            }
''',
    "AlicePollingManager app and remote trunk dispatch",
)

s = once(
    s,
    '''                data.windowFL?.let { put("windowFL", it) }
                data.windowFR?.let { put("windowFR", it) }
                data.windowRL?.let { put("windowRL", it) }
                data.windowRR?.let { put("windowRR", it) }
                data.sunroof?.let { put("sunroof", it) }
                data.trunk?.let { put("trunk", it) }
                data.lockFL?.let { put("lockFL", it) }
                data.acStatus?.let { put("acStatus", it) }
                data.acTemp?.let { put("acTemp", it) }
                data.acCirc?.let { put("acCirc", it) }
                data.insideTemp?.let { put("insideTemp", it) }
''',
    '''                data.soc?.let { put("soc", it) }
                data.speed?.let { put("speed", it) }
                data.gear?.let { put("gear", it) }
                data.powerState?.let { put("powerState", it) }
                data.exteriorTemp?.let { put("exteriorTemp", it) }
                data.insideTemp?.let { put("insideTemp", it) }

                data.acStatus?.let { put("acStatus", it) }
                data.acTemp?.let { put("acTemp", it) }
                data.fanLevel?.let { put("fanLevel", it) }
                data.acCirc?.let { put("acCirc", it) }
                data.acDefrostFront?.let { put("acDefrostFront", it) }
                data.acWindMode?.let { put("acWindMode", it) }
                data.acCtrlMode?.let { put("acCtrlMode", it) }

                data.windowFL?.let { put("windowFL", it) }
                data.windowFR?.let { put("windowFR", it) }
                data.windowRL?.let { put("windowRL", it) }
                data.windowRR?.let { put("windowRR", it) }
                data.doorFL?.let { put("doorFL", it) }
                data.doorFR?.let { put("doorFR", it) }
                data.doorRL?.let { put("doorRL", it) }
                data.doorRR?.let { put("doorRR", it) }
                data.sunroof?.let { put("sunroof", it) }
                data.trunk?.let { put("trunk", it) }
                data.hood?.let { put("hood", it) }
                data.lockFL?.let { put("lockFL", it) }

                data.seatHeatDriver?.let { put("seatHeatDriver", it) }
                data.seatVentDriver?.let { put("seatVentDriver", it) }
                data.seatHeatPassenger?.let { put("seatHeatPassenger", it) }
                data.seatVentPassenger?.let { put("seatVentPassenger", it) }

                data.driveMode?.let { put("driveMode", it) }
                data.drl?.let { put("drl", it) }
                data.lightLow?.let { put("lightLow", it) }
                data.turnSignal?.let { put("turnSignal", it) }
''',
    "expanded bridge telemetry",
)

p.write_text(s)

print("Alice 5.1 app/vehicle bridge applied: version 64012, broad semantic test surface")
