#!/usr/bin/env python3
from pathlib import Path


def once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f"Alice5.1 anchor missing: {label}")
    return text.replace(old, new, 1)

# Identity: 5.1 is an update over the validated 5.0 command bridge.
p = Path("app/build.gradle.kts")
s = p.read_text()
s = once(s, "versionCode = 64011", "versionCode = 64012", "versionCode")
s = once(
    s,
    'versionName = "3.15.2-alice5.0-command-bridge"',
    'versionName = "3.15.2-alice5.1-app-bridge"',
    "versionName",
)
p.write_text(s)

# AlicePollingManager is generated by Build 5.0. Extend it after that hardened
# baseline is installed so app-launch actions remain completely separate from
# BYD vehicle commands and their allowlist/safety gates.
p = Path("app/src/main/kotlin/com/bydmate/app/data/remote/AlicePollingManager.kt")
s = p.read_text()

s = once(
    s,
    '''    private val sharedAdaptiveLoop: com.bydmate.app.data.loop.SharedAdaptiveLoop,\n    private val vehicleApi: VehicleApi,\n) {\n''',
    '''    private val sharedAdaptiveLoop: com.bydmate.app.data.loop.SharedAdaptiveLoop,\n    private val vehicleApi: VehicleApi,\n    private val appCommandDispatcher: AliceAppCommandDispatcher,\n) {\n''',
    "AlicePollingManager app dispatcher injection",
)

s = once(
    s,
    '''            val resolved = AliceBridgeCommandTranslator.resolve(cmd)\n            if (resolved == null) {\n                val requested = cmd.optString("action", "<missing>")\n                Log.w(TAG, "BRIDGE_COMMAND_REJECTED id=$id action=$requested reason=unsupported_or_invalid")\n                rememberResult(id, requested, false, "unsupported_or_invalid")\n                results += AckResult(id, false, "unsupported_or_invalid")\n                continue\n            }\n\n            val command = resolved.vehicleCommand\n''',
    '''            val requested = cmd.optString("action", "<missing>").trim().lowercase()\n\n            // Alice 5.1 app bridge. App-launch actions are handled before vehicle\n            // translation and never enter VehicleApi / raw BYD write paths.\n            val appResult = appCommandDispatcher.dispatch(requested)\n            if (appResult != null) {\n                val success = appResult.isSuccess\n                val error = appResult.exceptionOrNull()?.message\n                Log.i(TAG, "BRIDGE_APP_COMMAND_RECEIVED id=$id action=$requested")\n                rememberResult(id, requested, success, error)\n                Log.i(TAG, "BRIDGE_APP_COMMAND_RESULT id=$id action=$requested success=$success" +\n                    (error?.let { " error=${it.take(160)}" } ?: ""))\n                results += AckResult(id, success, error?.take(240))\n                continue\n            }\n\n            val resolved = AliceBridgeCommandTranslator.resolve(cmd)\n            if (resolved == null) {\n                Log.w(TAG, "BRIDGE_COMMAND_REJECTED id=$id action=$requested reason=unsupported_or_invalid")\n                rememberResult(id, requested, false, "unsupported_or_invalid")\n                results += AckResult(id, false, "unsupported_or_invalid")\n                continue\n            }\n\n            val command = resolved.vehicleCommand\n''',
    "AlicePollingManager app action dispatch",
)

p.write_text(s)

print("Alice 5.1 app bridge applied: version 64012, app.waze.open support")
